### ISSUE TITLE
Having Issues in Downloading Buildings Data

### ISSUE THREAD

**Issue by simplysabir** [OvertureMaps/docs#105]
I was trynna download the buildings data from here 
https://docs.overturemaps.org/getting-data/duckdb/?query=Buildings

one thing that was weird to me was every other data was available in s3 but for buildings there's only option to fetch from azure. i was looking for the s3 alternative. isn't there a way? and why do we need to put account key if we're doing it via azure. ideally I'm looking for a way to download it from s3 only.

**Comment by skmoore** [comment]
You can download all the data themes from s3, you just need to change the fields you want in the `SELECT` statement and point to the correct data theme and type in the `WHERE` clause, something like:

```
SELECT
        id,
        type,
        subtype,
        class,
        has_parts,
        names.primary as name,
	height,
        geometry
FROM read_parquet('s3://overturemaps-us-west-2/release/2024-08-20.0/theme=buildings/type=building/*', filename=true, hive_partitioning=1)
```

**Comment by simplysabir** [comment]
thanks it worked!!
