### ISSUE TITLE
Overture + Pandas notebook not working

### ISSUE THREAD

**Issue by raybellwaves** [OvertureMaps/docs#111]
I'm trying to run the code in https://docs.overturemaps.org/examples/pandas/#13/47.6/-122.33/0/45

When I run

```
%%sql gulf_water <<
SELECT 
    id, 
    names.primary AS primary_name,
    ST_AsText(geometry) as geometry
FROM 
    read_parquet('s3://overturemaps-us-west-2/release/2024-09-18.0/theme=base/type=water/*', filename=true, hive_partitioning=1)
WHERE 
    bbox.xmin >= -91.3994
        and bbox.xmax <= -89.3864
        and bbox.ymin >= 29.152
        and bbox.ymax <= 30.5161
```

I get 

No function matches the given name and argument types 'ST_AsText(BLOB)'. You might need to add explicit type casts.
	Candidate functions:
	ST_AsText(POINT_2D) -> VARCHAR
	ST_AsText(LINESTRING_2D) -> VARCHAR
	ST_AsText(POLYGON_2D) -> VARCHAR
	ST_AsText(BOX_2D) -> VARCHAR
	ST_AsText(GEOMETRY) -> VARCHAR

**Comment by jenningsanderson** [comment]
Hi @raybellwaves — This is likely due to the version of DuckDB. DuckDB 1.1 now supports reading geoparquet without explicitly casting the geometry column. 

Try updating your version of DuckDB and please let me know if that works.

**Comment by raybellwaves** [comment]
taking a look.

FYI there's a mismatch between the docs (https://docs.overturemaps.org/examples/pandas/#13/47.6/-122.33/0/45; https://github.com/OvertureMaps/docs/blob/main/docs/examples/pandas.mdx) and the notebook at the notebook sharing space link (https://notebooksharing.space/view/1d0d72d24ed82d22a8101377ca811ab7365b6a67dac98f3add034719c44b537f#displayOptions=)

**Comment by raybellwaves** [comment]
![Screenshot 2024-09-26 at 4 18 55 PM](https://github.com/user-attachments/assets/5e24942d-6ce2-4f8b-878d-463fdaa3b973)

Looks ok now

duckdb==1.1.0
duckdb_engine==0.13.2
