### ISSUE TITLE
Not able to view Overture data on QGIS

### ISSUE THREAD

**Issue by nagashreepoojari07** [OvertureMaps/docs#138]
Hi,

I'm using duck DB to fetch data as a geo package file.
my code as per the duckdb documentation:

import duckdb as duck

db = duck.connect()
db.execute("INSTALL spatial")
db.execute("INSTALL httpfs")
db.execute("""
LOAD spatial;
LOAD httpfs;
SET s3_region='us-west-2';
""")

query = """
COPY(                                      
    SELECT
       id,
       names.primary as name,
       geometry                             
    FROM read_parquet('s3://overturemaps-us-west-2/release/2024-11-13.0/theme=divisions/type=division/*', filename=true, hive_partitioning=1)
    WHERE subtype='country'
) TO 'division_country.gpkg' WITH (FORMAT GDAL, DRIVER 'GPKG');
"""
db.execute(query)

I'm not able to view the data when i upload it in QGIS, looks like geometry is not getting recognized.
duckDB version:1.1.0
QGIS FDAL version: 3.6.1

**Comment by jeffdefacto** [comment]
This query is working for me as is, but you could try wrapping geometry in `ST_AsWKB(geometry)` to see if that fixes the issue.

**Comment by jenningsanderson** [comment]
This query works for me as well, can you confirm your DuckDB version that you're importing in  _python_?

`duck.__version__` mine is v1.1.3, while I have `duckdb --version` = v1.1.0

**Comment by nagashreepoojari07** [comment]
Thank you @jenningsanderson 
I was using duckDB version 1.0.0, upgrading to the latest fixed the issue.
