### ISSUE TITLE
Link to Places Schema is 404

### ISSUE THREAD

**Issue by tom-flamelit** [OvertureMaps/docs#64]
https://github.com/OvertureMaps/docs/blob/main/schema/reference/places/place

Clicking through into this is a 404 on public-facing github

**Comment by jenningsanderson** [comment]
Hi @tom-flamelit, where are you finding that path? 

The correct path for the schema documentation is on the hosted website: 
https://docs.overturemaps.org/schema/reference/places/place/

The schema itself is found on Github under the `schema` repository: 
https://github.com/OvertureMaps/schema/blob/main/schema/places/place.yaml

Does that clear up your question?
