### ISSUE TITLE
Explorer only allows downloads of building

### ISSUE THREAD

**Issue by thesteve0** [OvertureMaps/docs#98]
From my experience and in talking to the engineers you can only download the buildings layer in explorer. It would be really nice if explorer worked the way mentioned in the current doc. Unfortunately I don't think it does

https://docs.overturemaps.org/guides/divisions/#data-usage-guidelines

**Comment by jenningsanderson** [comment]
This is being addressed in the next major update!

**Comment by thesteve0** [comment]
Woot woot!
